### ISSUE TITLE
Multiple models?

### ISSUE THREAD

**Issue by el2ro** [JasonCraftsCode/dynamodb-datamodel#27]
Hi, 
I was looking for a library to use DynamoDb as a single table design and this lib looks promising.
I could not find an example of how to use this with multiple models in a single table, except when having embedded models. Is there a way to use multiple Models in a Single Table? (The definition of the returned model should be left to the user who defines the access patterns)

**Comment by JasonCraftsCode** [comment]
Yes I am working on the documentation and adding examples, hope to have this updated soon.
